### ISSUE TITLE
v0.24: bindingsContractVersion mismatch

### ISSUE THREAD

**Issue by kegsay** [NordSecurity/uniffi-bindgen-go#23]
When generating bindings on #13 the `func uniffiCheckChecksums() {` fails due to `bindingsContractVersion := 23` still, when it should be 24 I think? Swapping this value to 24 stops it panicking and let's things continue.

**Comment by arg0d** [comment]
The problem is that #13 is pinned on commit somewhere between 0.24.3 and 0.25.0. Actual `0.24` is supposed to have `UNIFFI_CONTRACT_VERSION = 22`, and it seems like #13 has `UNIFFI_CONTRACT_VERSION = 23`. #13 needs to be rebased to either `0.24` or `0.25`.

`bindingsContractVersion` does not have to correspond to uniffi versions. See https://github.com/mozilla/uniffi-rs/issues/1800.

**Comment by arg0d** [comment]
I think this can be closed, right?

**Comment by kegsay** [comment]
Yes
